version: '3.7'
services:

    webservice:
        image: docker.koldskl.xyz/dmr-webservice
        networks:
          net:
            ipv4_address: 172.20.1.15
        depends_on:
            - db-mongo
        restart: unless-stopped
        environment:
            MONGODB_CONNECTION_STRING: mongodb://mongo:27017

    mongo:
        image: mongodb/mongodb-community-server:latest
        container_name: db-mongo
        volumes:
          - mongo_data:/data/db

volumes:
    mongo_data:  
  

networks:
    net:
        name: myNetwork
        external: true